# Generated by Django 5.2 on 2025-04-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="Название курса"),
                ),
                (
                    "course_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/preview/",
                        verbose_name="превью курса",
                    ),
                ),
                (
                    "course_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_name",
                    models.CharField(max_length=200, verbose_name="Название урока"),
                ),
                (
                    "lesson_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/preview/",
                        verbose_name="превью урока",
                    ),
                ),
                (
                    "lesson_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание урока"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["course", "lesson_name"],
            },
        ),
    ]
