# Generated by Django 5.2 on 2025-04-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course", "name"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_preview",
            new_name="preview",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson_preview",
            new_name="preview",
        ),
    ]
